# Generated by Django 5.2.17 on 2026-09-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ImageField(default=None, upload_to='vehicle_images/'),
            preserve_default=False,
        ),
    ]
