# Generated by Django 5.2.17 on 2026-09-03 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiallisting',
            old_name='unit_price',
            new_name='price_per_unit',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image',
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
