# Generated by Django 5.2.17 on 2026-09-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_unit_price_materiallisting_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
