# Generated by Django 5.2.17 on 2026-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric')], default='DIESEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('EXCAVATOR', 'Excavator'), ('LOADER', 'Loader'), ('DUMPER', 'Dumper'), ('CRANE', 'Crane'), ('BACKHOE', 'Backhoe'), ('ROLLER', 'Roller'), ('TRACTOR', 'Tractor'), ('TIPPER', 'Tipper'), ('JCB', 'JCB'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
